theme: jekyll-theme-minimal

title: China Business Research Network
title: 中国管理研究网络

CBRN mission statement
 
The China Business Research Network (CBRN) is jointly organized by researchers at the Chinese University of Hong Kong (Shenzhen), National University of Singapore, Peking University, the University of Southern California, and the University of Toronto. The primary objective of CBRN is to promote a deep understanding of China’s business environment through the lens of high-quality academic research. Through monthly seminars and other activities, we hope to provide a neutral platform for academic researchers around the world to discuss cutting-edge China-related topics across various business fields, including but not limited to accounting, finance, information systems, and management. Over time, we hope that CBRN can become a central intellectual hub that provides researchers in business and other related disciplines with the opportunity to network with colleagues with similar research interests on a regular basis and better understand China and its business environment.

CBRN seminar format
 
The seminars will be hosted on a monthly basis starting September 2021, and will take place over Zoom on Wednesdays 9:00-10:30am CST/SGT; Tuesdays 6:00-7:30pm PST; Tuesdays 9:00-10:30pm EST. Each seminar will consist of a 1.5-hour presentation including Q&As. 
We expect the participants of the seminars to be active researchers and PhD students all over the world. We also expect the audience to be diverse as we hope to promote interdisciplinary research across various business fields and other disciplines.
As CBRN is about China, the papers to be presented will be directly related to China or have significant implications for China (e.g., papers using a new research methodology that will be of significant interest to China-focused researchers). We especially welcome papers that cover new research areas, use new data sources (e.g., big data), or use new research methods (e.g., machine learning).

Seminar Schedule
Upcoming events
Coming soon
 
CBRN Committee
Advising Committee 
 
Nan Jia (USC)
Bin Ke (NUS)
Hai Lu (University of Toronto & Peking U)
T.J. Wong (USC)
Tianyu Zhang (CUHK Shenzhen)
 
Organizing Committee 
 
Changyi Chen (NUS)
AJ Yuan Chen (USC)
Serene Huang (Peking U)
Mingyue Zhang (University of Toronto)
Shubo Zhang (CUHK)
 

